<?php
/**
 * Этот файл является частью библиотеки КупиВкредит.
 *
 * Все права защищены (c) 2012 «Тинькофф Кредитные Системы» Банк (закрытое акционерное общество)
 *
 * Информация о типе распространения данного ПО указана в файле LICENSE,
 * распространяемого вместе с исходным кодом библиотеки.
 *
 * This file is part of the KupiVkredit library.
 *
 * Copyright (c) 2012  «Tinkoff Credit Systems» Bank (closed joint-stock company)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Kupivkredit\Caller\CallerHTTP;
use Kupivkredit\Envelope;
use Kupivkredit\Caller\Exception\CallerException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-21 at 11:40:34.
 */
class CallerHTTPTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var CallerHTTP
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CallerHTTP;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Kupivkredit\Caller\CallerHTTP::call
	 */
	public function testCall()
	{
		$envelope = new Envelope(sprintf('<%1$s></%1$s>', Envelope::TAG));
		$envelope->addChild(Envelope::MESSAGE, '<test></test>');
		$envelope->addChild(Envelope::SIGN,    uniqid('sign'));

		$answer = $this->object->call('localhost', $envelope->asXML(), array(CURLOPT_PROXY => null));

		$this->assertInstanceOf('Kupivkredit\\Response', $answer);
	}
}
