<?php
/**
 * Этот файл является частью библиотеки КупиВкредит.
 *
 * Все права защищены (c) 2012 «Тинькофф Кредитные Системы» Банк (закрытое акционерное общество)
 *
 * Информация о типе распространения данного ПО указана в файле LICENSE,
 * распространяемого вместе с исходным кодом библиотеки.
 *
 * This file is part of the KupiVkredit library.
 *
 * Copyright (c) 2012  «Tinkoff Credit Systems» Bank (closed joint-stock company)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Kupivkredit\Kupivkredit;
use Kupivkredit\CallProvider\CallProvider;
use Kupivkredit\Response;
use Kupivkredit\Envelope;
use Kupivkredit\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-25 at 18:02:23.
 */
class CallProviderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CallProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
	    $requester = $this->getMock('Kupivkredit\RequestBuilder\IRequestBuilder');
	    $requester
	        ->expects($this->once())
		    ->method('build')
		    ->will($this->returnValue(new Request('<test></test>')));

	    $enveloper = $this->getMock('Kupivkredit\EnvelopeBuilder\IEnvelopeBuilder');
	    $enveloper
		    ->expects($this->once())
		    ->method('build')
		    ->will($this->returnValue(new Envelope('<test></test>')));

	    $caller = $this->getMock('Kupivkredit\Caller\ICaller');
	    $caller
		    ->expects($this->once())
		    ->method('call')
		    ->will($this->returnValue(new Response('<test></test>')));


        $this->object = new CallProvider($requester, $enveloper, $caller, '1-TEST001', '123qwe', '321ewq', Kupivkredit::HOST_TEST);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kupivkredit\CallProvider\CallProvider::call
     */
    public function testCall()
    {
       $result = $this->object->call(Kupivkredit::API_PING, array());

	   $this->assertInstanceOf('Kupivkredit\Response', $result);
    }
}
